
risk_thresholds: # Риски
  high: 80
  medium: 50
  low: 20


actions: # Политики действий
  high_risk:
    - "isolate_host"
    - "limit_speed:1mbps"
  medium_risk:
    - "alert_admin"
    - "scan_antivirus"


log_paths: # Логи
  nginx: "/var/log/nginx/access.log"
  firewall: "/var/log/ufw.log"