
risk: # Настройка приоритетов
  high: 80
  medium: 50
  low: 20

 
logs: # Пут к логам
  nginx: "/var/log/nginx/access.log"
  firewall: "/var/log/ufw.log"


policies: # Политика действий
  - risk_level: "high"
    actions:
      - "isolate_host"
      - "limit_speed:1mbps"
  - risk_level: "medium"
    actions:
      - "alert_admin"
      - "scan_ports"